using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Reflection;
using System.Text;

namespace BepinExJS.Plugin
{
    public static class TypeDefGenerator
    {
        public static Dictionary<string, string> GenerateDtsPerAssembly(params string[] targetAssemblyNames)
        {
            var results = new Dictionary<string, string>(StringComparer.OrdinalIgnoreCase);
            var assemblies = AppDomain.CurrentDomain.GetAssemblies();
            bool matchAll = targetAssemblyNames != null && targetAssemblyNames.Any(t => t == "*" || t.Equals("all", StringComparison.OrdinalIgnoreCase));

            var filtered = assemblies.Where(a =>
            {
                var name = a.GetName().Name;
                if (matchAll) return true;
                if (targetAssemblyNames == null || targetAssemblyNames.Length == 0)
                {
                    return name == "Assembly-CSharp";
                }
                return targetAssemblyNames.Any(t => name.Equals(t, StringComparison.OrdinalIgnoreCase) || name.StartsWith(t, StringComparison.OrdinalIgnoreCase));
            }).ToList();

            foreach (var asm in filtered)
            {
                var name = asm.GetName().Name ?? "Unknown";
                var dts = GenerateDtsForAssembly(asm);
                if (!string.IsNullOrEmpty(dts))
                {
                    results[name] = dts;
                }
            }

            return results;
        }

        public static string GenerateDtsForAssembly(Assembly asm)
        {
            var asmName = asm.GetName().Name ?? "Unknown";
            Type[] types;
            try { types = asm.GetTypes(); }
            catch (ReflectionTypeLoadException ex) { types = ex.Types.Where(t => t != null).ToArray()!; }
            catch { return string.Empty; }

            var typesByNamespace = new Dictionary<string, List<Type>>();
            foreach (var t in types)
            {
                if (t == null || !t.IsPublic || t.IsNested) continue;
                var ns = string.IsNullOrEmpty(t.Namespace) ? "Global" : t.Namespace;
                if (!typesByNamespace.TryGetValue(ns, out var list))
                {
                    list = new List<Type>();
                    typesByNamespace[ns] = list;
                }
                list.Add(t);
            }

            if (typesByNamespace.Count == 0) return string.Empty;

            var sb = new StringBuilder();
            sb.AppendLine($"// Auto-generated TypeScript definitions for Assembly: {asmName}");
            sb.AppendLine("// Generated by BepinExJS TypeGen");
            sb.AppendLine();
            sb.AppendLine("declare namespace CS {");

            foreach (var kvp in typesByNamespace.OrderBy(k => k.Key))
            {
                sb.AppendLine($"  namespace {kvp.Key} {{");
                foreach (var type in kvp.Value.OrderBy(t => t.Name))
                {
                    GenerateTypeDefinition(sb, type, "    ");
                }
                sb.AppendLine("  }");
            }

            sb.AppendLine("}");
            return sb.ToString();
        }

        public static string GenerateDtsForLoadedAssemblies(params string[] targetAssemblyNames)
        {
            var perAsm = GenerateDtsPerAssembly(targetAssemblyNames);
            if (perAsm.Count == 0)
            {
                return "// No types found for specified assemblies.\ndeclare namespace CS {}\n";
            }

            var sb = new StringBuilder();
            sb.AppendLine("// Auto-generated TypeScript definitions for Unity Game Assemblies");
            sb.AppendLine("// Generated by BepinExJS TypeGen");
            sb.AppendLine();
            sb.AppendLine("declare namespace CS {");

            var assemblies = AppDomain.CurrentDomain.GetAssemblies();
            bool matchAll = targetAssemblyNames != null && targetAssemblyNames.Any(t => t == "*" || t.Equals("all", StringComparison.OrdinalIgnoreCase));

            var filtered = assemblies.Where(a =>
            {
                var name = a.GetName().Name;
                if (matchAll) return true;
                if (targetAssemblyNames == null || targetAssemblyNames.Length == 0)
                {
                    return name == "Assembly-CSharp";
                }
                return targetAssemblyNames.Any(t => name.Equals(t, StringComparison.OrdinalIgnoreCase) || name.StartsWith(t, StringComparison.OrdinalIgnoreCase));
            });

            // Group by namespace across all matched assemblies
            var typesByNamespace = new Dictionary<string, List<Type>>();

            foreach (var asm in filtered)
            {
                Type[] types;
                try { types = asm.GetTypes(); }
                catch (ReflectionTypeLoadException ex) { types = ex.Types.Where(t => t != null).ToArray()!; }
                catch { continue; }

                foreach (var t in types)
                {
                    if (t == null || !t.IsPublic || t.IsNested) continue;
                    var ns = string.IsNullOrEmpty(t.Namespace) ? "Global" : t.Namespace;
                    if (!typesByNamespace.TryGetValue(ns, out var list))
                    {
                        list = new List<Type>();
                        typesByNamespace[ns] = list;
                    }
                    list.Add(t);
                }
            }

            foreach (var kvp in typesByNamespace.OrderBy(k => k.Key))
            {
                sb.AppendLine($"  namespace {kvp.Key} {{");
                foreach (var type in kvp.Value.OrderBy(t => t.Name))
                {
                    GenerateTypeDefinition(sb, type, "    ");
                }
                sb.AppendLine("  }");
            }

            sb.AppendLine("}");
            return sb.ToString();
        }

        private static void GenerateTypeDefinition(StringBuilder sb, Type type, string indent)
        {
            var typeName = SanitizeIdentifier(type.Name.Split('`')[0]);

            if (type.IsEnum)
            {
                sb.AppendLine($"{indent}enum {typeName} {{");
                foreach (var name in Enum.GetNames(type))
                {
                    sb.AppendLine($"{indent}  {name},");
                }
                sb.AppendLine($"{indent}}}");
                return;
            }

            var kind = type.IsInterface ? "interface" : "class";
            sb.AppendLine($"{indent}export {kind} {typeName} {{");

            // Static properties & fields
            var flags = BindingFlags.Public | BindingFlags.Static | BindingFlags.Instance | BindingFlags.DeclaredOnly;

            foreach (var field in type.GetFields(flags))
            {
                if (field.IsSpecialName) continue;
                var mod = field.IsStatic ? "static " : "";
                var fieldName = SanitizeIdentifier(field.Name);
                sb.AppendLine($"{indent}  {mod}{fieldName}: {MapType(field.FieldType)};");
            }

            foreach (var prop in type.GetProperties(flags))
            {
                if (prop.IsSpecialName) continue;
                var mod = (prop.GetGetMethod()?.IsStatic ?? false) ? "static " : "";
                var propName = SanitizeIdentifier(prop.Name);
                sb.AppendLine($"{indent}  {mod}{propName}: {MapType(prop.PropertyType)};");
            }

            // Methods
            var seenMethods = new HashSet<string>();
            foreach (var method in type.GetMethods(flags))
            {
                if (method.IsSpecialName) continue;
                var mod = method.IsStatic ? "static " : "";
                var methodName = SanitizeIdentifier(method.Name);
                var key = $"{mod}{methodName}_{method.GetParameters().Length}";
                if (seenMethods.Contains(key)) continue;
                seenMethods.Add(key);

                var paramList = string.Join(", ", method.GetParameters().Select(p => $"{SanitizeIdentifier(p.Name ?? "arg")}: {MapType(p.ParameterType)}"));
                sb.AppendLine($"{indent}  {mod}{methodName}({paramList}): {MapType(method.ReturnType)};");
            }

            sb.AppendLine($"{indent}}}");
        }

        private static string MapType(Type type)
        {
            if (type == typeof(void)) return "void";
            if (type == typeof(string) || type == typeof(char)) return "string";
            if (type == typeof(bool)) return "boolean";
            if (type.IsPrimitive || type == typeof(decimal)) return "number";
            if (type.IsArray) return $"{MapType(type.GetElementType()!)}[]";
            if (type.IsGenericType && type.GetGenericTypeDefinition() == typeof(List<>))
                return $"{MapType(type.GetGenericArguments()[0])}[]";

            return "any";
        }

        private static string SanitizeIdentifier(string name)
        {
            if (string.IsNullOrEmpty(name)) return "arg";
            if (name == "function" || name == "var" || name == "let" || name == "class" || name == "enum" || name == "default" || name == "delete")
                return $"_{name}";
            return new string(name.Select(c => char.IsLetterOrDigit(c) || c == '_' ? c : '_').ToArray());
        }
    }
}
